

# testing file

TERRORSRC=testError.cpp ../include/BtError.h ../src/BtError.cpp 
testError=testErr
CC=g++
INCL= -I ../include/
CXXFLAG=-Wall -g

$(testError):
	$(CC) $(CXXFLAG) $(INCL) -o testErr $(TERRORSRC)

